### ISSUE TITLE
Repository is only accessible via https

### ISSUE THREAD

**Issue by eejd** [int-brain-lab/paper-brain-wide-map#1]
For reasons that I cannot determine without admin rights, this repo, as opposed to the rest of the IBL repos, only allows HTTPS access. I can clone via https, but not ssh. However, my git workflows are all ssh based, so I cannot pull/push to this repo from many of my git tools. Can ssh access be verified or added to this repo?

**Comment by oliche** [comment]
Agreed, I think all repos have SSH access by default as of 2024 (not sure about 2021).
