### ISSUE TITLE
Release new spike sorting data on openalyx

### ISSUE THREAD

**Issue by oliche** [int-brain-lab/paper-brain-wide-map#71]
We will split the good units and spikes and the full spike sorting output:

- good units will figure within the current ALF format and architecture
- we add a table containing the full output, preferably column based and compressed.

Completion metric:
- the data can be loaded with spike sorting loader

Coordinate with int-brain-lab/ibllib#774, int-brain-lab/ibllib#775, int-brain-lab/ibllib#77

**Comment by chris-langfield** [comment]
WIP: https://github.com/int-brain-lab/iblalyx/pull/68

**Comment by chris-langfield** [comment]
Data request form: https://docs.google.com/document/d/15HssSL7LxKs35grijn6eUJq-hjgDiw7H-tHhg2syO3E/edit
