### ISSUE TITLE
Motor correlates code review

### ISSUE THREAD

**Issue by themattinthehatt** [int-brain-lab/paper-brain-wide-map#8]
initial code review for `paper-brain-wide-map/motor_correlates/fig_motor_correlates_prior.py`

Documentation
--------------------
* add README.md that explains what analysis the module is designed for, and how to produce an example plot for a single eid, as well as the across-session barplots (basically, illustrate the instructions you sent me on slack) (importantly, need to fix hard-coded paths for this to be possible, see comment below)
* add some basic docstrings to each function (especially important to document/detail function arguments)

Code
-------
* lots of unused import statements could be cut
* the hard-coded variable `behave7` appears in multiple places, this could be moved to top of file (you could even automatically define it as the keys of variable `sr` or something)
* various functions have hard-coded paths: `get_allen_info`, `get_PSTHs_7behaviors`, `Result_7behave`, `per_trial_scatters`, `compare_neuro_whisk`, `paw_position_onframe`, `res_to_df`. most of these you could just include the save/load path as an additional argument to the function. 
* an easy path fix for `paw_position_onframe` would be to just save a frame from that particular eid in the repo so you can load it from anywhere; otherwise we'd need to expect people to download a video frame from the server
* is the color palette for `get_allen_info` used across the paper? if so this function should be moved to a more central place
* I think it makes sense to move all the code for the intro figure (i.e. code after L781) into it's own file so that `fig_motor_correlates_prior.py` just produces the motor correlate figure
* `generate_pseudo_blocks`: can this be imported from elsewhere, surely we use somthing like this all over the repo
* `get_licks`: can this be imported from brainbox?
* are these functions used anywhere? `whisker_inspection`, `per_trial_scatters`, `compare_neuro_whisk`

@mschart this is a first pass, let me know when you're ready for the next round. the most important thing i think is for me to be able to make some example plots myself by following instructions in a README.

**Comment by mschart** [comment]
Greetings Matt, thanks a lot for these great ideas to make the script more user-friendly. Maybe have a go and tell me if there's still something that needs fixing? Thanks!

**Comment by themattinthehatt** [comment]
@mschart I was able to run everything on my end and reproduce plots from the public database :fireworks: 

A final suggestion would be to use 
`img_file = os.path.join(os.path.dirname(__file__), '15f742e1-1043-45c9-9504-f1e8a53c1744_left.npy)' 
in the function `paw_position_onframe` so that a user doesn't have to manually move that file around on their computer. Otherwise looks good :heavy_check_mark:

**Comment by mschart** [comment]
@themattinthehatt thank you for test running! I did your last point also, good idea.
